---
- name: NGINX | Install'e'config NGINX server, mc first
  hosts: nginx
  become: true
  vars:
    nginx_port_to_listen: 8080
  
  tasks:
    - name: Install mc first, just for fun!
      dnf:
        name: mc
        state: present
    
    - name: Install EPEL repo package
      dnf:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages
    
    - name: Install NGINX from EPEL repo
      dnf:
        name: nginx
        state: latest
      notify:
        - restart nginx
      tags:
        - nginx-package
        - packages

    - name: Cofiguring NGINX by j2 template config file
      template:
        src: ../templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
         - reload nginx  
      tags:
         - nginx-configuration

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restart

    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded


